version: 3

tasks:
  build:
    desc: Build
    cmds:
      - go mod tidy
      - go build ./...
      - goreleaser build --snapshot --clean --single-target --output dist/expframework

  outdated:
    desc: Show dependency updates
    aliases: [ dependencyUpdates ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  lint:
    desc: Lint
    cmds:
      - golangci-lint run

  mingo:
    cmds:
      - mingo -tests -v

  test-camera-capture:
    deps: [ build ]
    cmds:
      - dist/expframework test camera capture {{.CLI_ARGS}}
    env:
      CONFIG_FILE: .test/cameraCapture/config.yml
      LOG_LEVEL: debug

  test-camera-mjpeg:
    deps: [ build ]
    cmds:
      - dist/expframework test camera mjpeg
    env:
      CONFIG_FILE: .test/cameraCapture/config.yml
      LOG_LEVEL: debug
